[package]
description = "FlightSQL server gateway backed by any ADBC driver"
authors.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true
name = "adbc-flightsql-gateway"
rust-version.workspace = true
version.workspace = true

[dependencies]
adbc.workspace = true
arrow-array.workspace = true
arrow-flight.workspace = true
arrow-ipc.workspace = true
arrow-schema.workspace = true
base64 = "0.22"
bytes.workspace = true
dashmap = "6"
futures-util.workspace = true
prost.workspace = true
rand = "0.9"
tokio.workspace = true
tonic.workspace = true

[dev-dependencies]
adbc-flightsql.workspace = true
adbc-mysql.workspace = true
adbc-postgres.workspace = true
adbc-sqlite.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
arrow-select.workspace = true
tokio = { workspace = true, features = ["net"] }
tokio-stream.workspace = true
tonic.workspace = true
